task_data = [

# ================= EMAIL (50) =================

("write a leave email", "email"),
("send mail to manager", "email"),
("compose professional email", "email"),
("write apology email", "email"),
("draft complaint email", "email"),
("email to HR for leave", "email"),
("request salary increment email", "email"),
("write business email", "email"),
("compose formal letter", "email"),
("send meeting invitation email", "email"),
("email to professor", "email"),
("write follow up email", "email"),
("inform sick leave by email", "email"),
("request permission email", "email"),
("email about project update", "email"),
("write resignation email", "email"),
("compose client email", "email"),
("send reminder email", "email"),
("write appreciation email", "email"),
("email for job inquiry", "email"),
("write internship request email", "email"),
("mail to team leader", "email"),
("email for project submission", "email"),
("send confirmation email", "email"),
("write email for delay apology", "email"),
("compose welcome email", "email"),
("write email to bank", "email"),
("email to customer support", "email"),
("professional leave request mail", "email"),
("email for meeting reschedule", "email"),
("mail to college office", "email"),
("email to teacher", "email"),
("write request email", "email"),
("send greeting email", "email"),
("email about system issue", "email"),
("complaint mail to company", "email"),
("write email for feedback", "email"),
("mail to HR for documents", "email"),
("email for job application", "email"),
("follow up mail after interview", "email"),
("email to supplier", "email"),
("email for training request", "email"),
("write notice email", "email"),
("email to confirm appointment", "email"),
("write introduction email", "email"),
("send invitation mail", "email"),
("email to cancel meeting", "email"),
("mail for holiday request", "email"),
("write mail to boss", "email"),
("email to client for update", "email"),

# ================= RESUME (50) =================

("write a resume", "resume"),
("create a resume", "resume"),
("build my CV", "resume"),
("generate resume for job", "resume"),
("make resume for software engineer", "resume"),
("professional resume writing", "resume"),
("create CV for fresher", "resume"),
("resume for internship", "resume"),
("update my resume", "resume"),
("write biodata", "resume"),
("prepare job resume", "resume"),
("create resume for developer", "resume"),
("build CV for data analyst", "resume"),
("resume for mechanical engineer", "resume"),
("resume for teacher job", "resume"),
("design resume format", "resume"),
("resume for college student", "resume"),
("create CV for job application", "resume"),
("resume for python developer", "resume"),
("resume for fresher engineer", "resume"),
("resume for MBA student", "resume"),
("resume for part time job", "resume"),
("resume for IT professional", "resume"),
("resume for internship application", "resume"),
("resume for job interview", "resume"),
("write professional CV", "resume"),
("resume for marketing role", "resume"),
("resume for manager position", "resume"),
("resume for accountant", "resume"),
("resume for business analyst", "resume"),
("resume for HR role", "resume"),
("resume for civil engineer", "resume"),
("resume for final year student", "resume"),
("resume for experienced candidate", "resume"),
("resume for technical job", "resume"),
("resume template creation", "resume"),
("resume for entry level job", "resume"),
("resume for graphic designer", "resume"),
("resume for banking job", "resume"),
("resume for government job", "resume"),
("resume for job switch", "resume"),
("resume for software tester", "resume"),
("resume for project manager", "resume"),
("resume for Android developer", "resume"),
("resume for web developer", "resume"),
("resume for UI designer", "resume"),
("resume for fresher CV format", "resume"),
("resume writing help", "resume"),
("create strong resume", "resume"),
("resume building assistance", "resume"),

# ================= CODING (50) =================

("write python code", "coding"),
("create login system in python", "coding"),
("build REST API in django", "coding"),
("java program for sorting", "coding"),
("write c++ program", "coding"),
("create calculator in python", "coding"),
("write html login page", "coding"),
("fix bug in python code", "coding"),
("generate sql query", "coding"),
("write javascript function", "coding"),
("create flask app", "coding"),
("code for student management system", "coding"),
("develop authentication system", "coding"),
("create banking system program", "coding"),
("write java login system", "coding"),
("build website using html css", "coding"),
("write react component", "coding"),
("create API in node js", "coding"),
("write program for prime numbers", "coding"),
("sort array in python", "coding"),
("binary search program", "coding"),
("linked list implementation", "coding"),
("stack implementation in java", "coding"),
("queue program in c++", "coding"),
("django CRUD application", "coding"),
("python file handling program", "coding"),
("create chatbot in python", "coding"),
("create game using python", "coding"),
("write program for factorial", "coding"),
("find palindrome in java", "coding"),
("write code for login form", "coding"),
("css animation code", "coding"),
("javascript validation code", "coding"),
("build blog website code", "coding"),
("create REST service", "coding"),
("code for OTP verification", "coding"),
("python GUI application", "coding"),
("Tkinter calculator", "coding"),
("write multithreading code", "coding"),
("write recursion example", "coding"),
("code for database connection", "coding"),
("implement search algorithm", "coding"),
("create portfolio website", "coding"),
("code for image upload", "coding"),
("write API integration code", "coding"),
("write socket programming code", "coding"),
("create mobile app logic", "coding"),
("create e-commerce backend", "coding"),
("write code for pagination", "coding"),
("create form submission logic", "coding"),

# ================= CREATIVE (50) =================

("write a love story", "creative"),
("tell a horror story", "creative"),
("write emotional story", "creative"),
("create short story", "creative"),
("write poem", "creative"),
("fantasy story about dragon", "creative"),
("motivational story", "creative"),
("sad story", "creative"),
("romantic poem", "creative"),
("imaginative story", "creative"),
("bedtime story", "creative"),
("story for kids", "creative"),
("mystery story", "creative"),
("science fiction story", "creative"),
("write song lyrics", "creative"),
("create drama scene", "creative"),
("write funny story", "creative"),
("write moral story", "creative"),
("create adventure story", "creative"),
("story about friendship", "creative"),
("story about success", "creative"),
("story about failure", "creative"),
("emotional poem", "creative"),
("love poem", "creative"),
("friendship poem", "creative"),
("story set in future", "creative"),
("story about hero", "creative"),
("story about college life", "creative"),
("story about childhood", "creative"),
("write a novel idea", "creative"),
("create character background", "creative"),
("write thriller story", "creative"),
("ghost story", "creative"),
("romantic short story", "creative"),
("dramatic story", "creative"),
("create movie script idea", "creative"),
("write inspirational story", "creative"),
("write poetic lines", "creative"),
("story about travel", "creative"),
("story about war", "creative"),
("story about animals", "creative"),
("story about nature", "creative"),
("creative writing prompt", "creative"),
("write emotional dialogue", "creative"),
("create fictional world", "creative"),
("write fantasy poem", "creative"),
("story about student life", "creative"),
("story about teacher", "creative"),
("write artistic content", "creative"),
("create storytelling content", "creative"),

# ================= EDUCATIONAL (50) =================

("explain machine learning", "educational"),
("teach python loops", "educational"),
("explain recursion", "educational"),
("what is artificial intelligence", "educational"),
("describe data structures", "educational"),
("explain neural networks", "educational"),
("teach me OOP concepts", "educational"),
("explain cloud computing", "educational"),
("what is deep learning", "educational"),
("explain database normalization", "educational"),
("teach java basics", "educational"),
("explain operating system", "educational"),
("explain computer networks", "educational"),
("teach html basics", "educational"),
("learn css fundamentals", "educational"),
("explain python functions", "educational"),
("teach algorithms", "educational"),
("explain sorting algorithms", "educational"),
("teach data science", "educational"),
("explain artificial neural networks", "educational"),
("teach statistics basics", "educational"),
("explain probability theory", "educational"),
("learn SQL basics", "educational"),
("explain blockchain technology", "educational"),
("teach cybersecurity basics", "educational"),
("explain internet working", "educational"),
("learn programming concepts", "educational"),
("explain virtualization", "educational"),
("teach linux commands", "educational"),
("explain web development", "educational"),
("teach mobile development", "educational"),
("explain big data", "educational"),
("explain IoT concepts", "educational"),
("teach machine learning models", "educational"),
("explain regression models", "educational"),
("teach classification algorithms", "educational"),
("explain NLP basics", "educational"),
("teach software engineering", "educational"),
("explain agile methodology", "educational"),
("teach git basics", "educational"),
("explain devops", "educational"),
("teach system design", "educational"),
("explain cloud architecture", "educational"),
("teach docker basics", "educational"),
("explain kubernetes", "educational"),
("teach python libraries", "educational"),
("explain AI applications", "educational"),
("teach coding fundamentals", "educational"),
("explain computer architecture", "educational"),
("teach programming logic", "educational"),

]

tone_data = [

# ================= PROFESSIONAL =================

("write professional email", "professional"),
("formal business communication", "professional"),
("official corporate tone", "professional"),
("formal writing style", "professional"),
("professional response", "professional"),
("corporate language", "professional"),
("formal job related message", "professional"),
("business presentation tone", "professional"),
("professional resume tone", "professional"),
("office communication style", "professional"),
("professional job application tone", "professional"),
("write like corporate email", "professional"),
("formal and structured response", "professional"),
("professional writing format", "professional"),
("workplace formal tone", "professional"),
("serious official writing", "professional"),
("formal academic tone", "professional"),
("professional documentation tone", "professional"),
("use official language", "professional"),
("professional report style", "professional"),

# ================= POLITE =================

("write politely", "polite"),
("polite request message", "polite"),
("respectful tone", "polite"),
("kind communication", "polite"),
("gentle response", "polite"),
("courteous writing style", "polite"),
("humble tone", "polite"),
("soft polite message", "polite"),
("polite email tone", "polite"),
("respectful explanation", "polite"),
("calm and polite tone", "polite"),
("nice request style", "polite"),
("graceful communication", "polite"),
("use polite language", "polite"),
("write in respectful manner", "polite"),
("considerate tone", "polite"),
("friendly but polite", "polite"),
("sincere tone", "polite"),
("calm polite explanation", "polite"),
("polite formal tone", "polite"),

# ================= FRIENDLY =================

("friendly tone", "friendly"),
("casual friendly message", "friendly"),
("talk like a friend", "friendly"),
("informal friendly writing", "friendly"),
("simple friendly explanation", "friendly"),
("light friendly communication", "friendly"),
("warm and friendly tone", "friendly"),
("friendly chat style", "friendly"),
("relaxed communication tone", "friendly"),
("friendly email style", "friendly"),
("approachable tone", "friendly"),
("conversational style", "friendly"),
("casual communication", "friendly"),
("friendly response format", "friendly"),
("easygoing tone", "friendly"),
("comfortable tone", "friendly"),
("natural talking style", "friendly"),
("friendly explanation", "friendly"),
("soft casual tone", "friendly"),
("friendly supportive tone", "friendly"),

# ================= WITTY =================

("funny tone", "witty"),
("humorous message", "witty"),
("add jokes", "witty"),
("sarcastic tone", "witty"),
("playful writing style", "witty"),
("entertaining tone", "witty"),
("make it humorous", "witty"),
("light funny communication", "witty"),
("comic storytelling style", "witty"),
("fun engaging tone", "witty"),
("joking manner", "witty"),
("funny response", "witty"),
("cheerful witty style", "witty"),
("add humor in message", "witty"),
("fun conversation tone", "witty"),
("light sarcasm tone", "witty"),
("creative funny tone", "witty"),
("humorous explanation", "witty"),
("playful storytelling", "witty"),
("funny casual style", "witty"),

# ================= NEUTRAL =================

("neutral tone", "neutral"),
("simple explanation", "neutral"),
("normal response style", "neutral"),
("basic communication", "neutral"),
("plain informative tone", "neutral"),
("standard writing style", "neutral"),
("direct explanation", "neutral"),
("balanced tone", "neutral"),
("objective response", "neutral"),
("clear neutral message", "neutral"),
("simple teaching tone", "neutral"),
("straightforward explanation", "neutral"),
("regular conversation style", "neutral"),
("standard email tone", "neutral"),
("informative neutral tone", "neutral"),
("plain simple tone", "neutral"),
("basic writing style", "neutral"),
("neutral professional tone", "neutral"),
("simple factual tone", "neutral"),
("calm neutral explanation", "neutral"),
]

